### ISSUE TITLE
Using Redis Stack and Pool Feature

### ISSUE THREAD

**Issue by tehsunnliu** [dahomey-technologies/rustis#12]
Hi, I was facing some trouble using Redis Stack and the pool features provided by this package. Is there any example or sample code where I can learn how to use those features of this package?

Thank you.

**Comment by mcatanzariti** [comment]
Hi @tehsunnliu,

The pool documentation is here with an example 
https://docs.rs/rustis/latest/rustis/client/index.html#the-pooled-client-manager

About RedisStack, like any other high level commands, it is available in the `commands` module where commands are gathered in differents traits implemented by the `Client` struct:
https://docs.rs/rustis/latest/rustis/commands

You will find RedisStack documentation on the different specific traits, for instance [JsonCommands](https://docs.rs/rustis/latest/rustis/commands/trait.JsonCommands.html) for RedisJson

Examples can be found in the test suite:
https://github.com/dahomey-technologies/rustis/blob/main/src/tests.
Each specific command trait should be tested here.

Which part of RedisStack do you want to use ?
I may help you on specific questions

**Comment by mcatanzariti** [comment]
Consider also using the [multiplexed client](https://docs.rs/rustis/0.7.2/rustis/client/index.html#the-multiplexer) instead of the pool.

**Comment by tehsunnliu** [comment]
Thank you so much @mcatanzariti for your reply and the sources you have provided. It's really helpful. 

I'm trying to add the Redis Stack feature to the [rocket_auth](https://github.com/tvallotton/rocket_auth) crate which currently supports MySQL, PostgreSQL, and SQLite. And uses Redis only for caching. Since I, recently came to know that Redis also supports Permanent data storage so I thought it will be a good time to learn Redis Stack and also implement this feature on the rocket_auth crate.

**Comment by mcatanzariti** [comment]
Don't hesitate if I can help you further
