### ISSUE TITLE
Should I use this library in production?

### ISSUE THREAD

**Issue by MrCasCode** [dahomey-technologies/rustis#13]
Hi,

First of all I just wanted to say thanks for all the work that has been put into this library, from what I've seen it seems great.

My question is related to maturity and production readiness. I'm starting a new project and I'm studying the possiblity to do it in rust. I'll need reliable redis streams support. 

How would you compare it in terms of maturity to the most popular out there `redis-rs`? 
Would you mind sharing the motivations or plans for this library?

Thanks!

**Comment by mcatanzariti** [comment]
Hi @MrCasCode,

To be totally transparent, my first requirement was to write a notification service based on pub/sub.

I tried a few libraries:

`redis-rs` is the most popular one but pub/sub is still synchronous
`redis-async-rs is too low-level, buggy and does not seem active anymore, even if their pub/sub implementation is async
`fred` is asynchronous & active but their pub/sub implementation is not flexible enough for my requirements.
Consequently I decided to write my own implementation of Redis for Rust with the first objective to learn Rust, that I discovered a year ago, and also to be full async, fully compliant with Redis 7.x & Redis-Stack and to offer a very flexible Pub/Sub implementation.
Finally I reached a point where I thought it could be interesting to share it in the official documentation.

I am still preparing a switch to serde, it will allow to reduce drastically allocations for conversions from a RESP buffer to a Rust struct/enum without using an intermediate and temporary resp::Value enum.

What are your plans with Redis ? Even if rustis is still young, I will be able to support you.

Thank you

**Comment by MrCasCode** [comment]
Thanks for your answer @mcatanzariti .

As a said, impressive work both on implemantation and on documentation.

It is a work project in the financial industry, so unfortunately I won't be able to use your library for now, but will keep an eye on your work and reevaluate when this has more adoption!
