### ISSUE TITLE
Redisearch object mapping - FtSearchResult to X

### ISSUE THREAD

**Issue by wojciechbator** [dahomey-technologies/rustis#39]
Hey, very nice job here - I see this supports both sentinel, json and search modules which is perfect for my use. I was searching through tests and examples of how the api can be used most efficiently and found out one thing I'm not sure of - about how to map `FtSearchResult` to a rust struct. Suppose I have a `JSON` list of fruits and I want to filter them by color, size etc. So I create an index on desired fields and suppose that I know exactly, I'll be able to narrow down result to an `Optional<Fruit>`. How's the best way/is it possible with some helpers to transform `FtSearchResult`.results into an exact rust struct? I suppose I could map `values` which is a Vec<String, String> for my needs? Is this vector some kind of a map of key->value? Any better way to map this, maybe by putting some directive on `Fruit` struct?

Update:
A quick check in redis docs: (https://redis.io/docs/interact/search-and-query/indexing/) and I think that this response corresponds to Redis response and in my case, second string from the vec will be stringified `Fruit` json granted that I specified I'm looking for the whole thing - `$`. I suppose, I should unmarshal string into `Fruit` by hand?

PS: Can you also support `redis-sentinel` protocol in connection string? It seems that it panics when it's provided.

Thanks in advance.

**Comment by mcatanzariti** [comment]
Hi @wojciechbator,

Thank you for the good words ^^
Could you provide a full example of your queries and the Fruit struct ?

About sentinel, it is supported in the connection string with a specific syntax:
https://docs.rs/rustis/latest/rustis/client/index.html#sentinel

Cheers,

Michaël

**Comment by mcatanzariti** [comment]
Hi again,

To give you a beginning of an answer on the FtSearchResult struct, yes, this struct is very generic and provides no facilities to help users deserialize results into rust user structs.
That said, based on your example, we could check together how to improve that matter.

Cheers,

Michaël

**Comment by wojciechbator** [comment]
Hi, I was just trying the thing out. IMO it's ok - FtSearchResult maps the response in generic way and one can extract results as needed. 

On a side note - consider also supporting protocols with hyphen, like `redis-sentinel` or `redis-cluster`. It's common to use them as such and when enum does not exist, the lib will panic.
