### ISSUE TITLE
Error reconnect in the master-replica model of Redis-Server with Redis Sentinel

### ISSUE THREAD

**Issue by lazyky** [dahomey-technologies/rustis#51]
**Description**
When the master node of redis-server crash, reconnecting will not obtain the address of the updated master node and generate an error:

```
Err(Client("Disconnected from server"))
```

**To Reproduce**
According to the [document](https://redis.io/docs/management/sentinel/) of redis.

- Build the master-replica model of Redis-Server with Redis Sentinel

```
       +----+
       | M1 |
       | S1 |
       +----+
          |
+----+    |    +----+
| R2 |----+----| R3 |
| S2 |         | S3 |
+----+         +----+

Masters are called M1, M2, M3, ..., Mn.
Replicas are called R1, R2, R3, ..., Rn (R stands for replica).
Sentinels are called S1, S2, S3, ..., Sn.
```

- Crash the master node of redis-server

**Additional context**

##### SentinelConnection
- I checked the code of [`SentinelConnection::reconnect()`](https://github.com/dahomey-technologies/rustis/blob/bd8637b59a619b49f283fe581ee19e2d5e639cd3/src/network/sentinel_connection.rs#L36-L38) and found that reconnecting using[`StandaloneConnection::reconnect()`](https://github.com/dahomey-technologies/rustis/blob/bd8637b59a619b49f283fe581ee19e2d5e639cd3/src/network/standalone_connection.rs#L172-L180) does not re-obtain the host and port of the updated master node

##### ClusterConnection
- Reconnect will use [`ClusterConnection::connect_to_cluster()`](https://github.com/dahomey-technologies/rustis/blob/bd8637b59a619b49f283fe581ee19e2d5e639cd3/src/network/cluster_connection.rs#L905-L926) in [`ClusterConnection::reconnect()`](https://github.com/dahomey-technologies/rustis/blob/bd8637b59a619b49f283fe581ee19e2d5e639cd3/src/network/cluster_connection.rs#L830-L842)  to re-obtain the host and port of the node

**Comment by mcatanzariti** [comment]
https://github.com/dahomey-technologies/rustis/commit/45d0d3a0b35e31881c64110272d59d0aad73c9c8
