### ISSUE TITLE
[Bug] Credentials overwrite during sentinel connection

### ISSUE THREAD

**Issue by wojciechbator** [dahomey-technologies/rustis#56]
Hi! In your sentinel connection flow you're overwriting the config username/password with sentinel ones, here:

https://github.com/dahomey-technologies/rustis/blob/29b2b5f66f058bec3b8374fec6eb548b1f2ce472/src/network/sentinel_connection.rs#L73-L74

Then, in the loop section, you're properly using creds to AUTH in HELLO command in the sentinel mode, then all good during obtaining master node address, but when connecting to the master node here: 

https://github.com/dahomey-technologies/rustis/blob/29b2b5f66f058bec3b8374fec6eb548b1f2ce472/src/network/sentinel_connection.rs#L112

It all falls apart due to the credentials still being sentinel ones. In case that someone has the same creds for sentinel and standard nodes, all is fine, but in my case, I have a valid configuration, where sentinel_username and sentinel_password are different than standard username/password. When you connect to master node, using sentinel creds won't work and you should use standard user/pass combination here. I see two solutions for this problems:

[Solution 1]
Add optional sentinel_username and sentinel_password in the config object to differentiate them from standard credentials. In redis they are a separate things, where you specify sentinel_password as a query param in URL. This way, during sentinel phase, you can use sentinel creds and later on standard creds.

[Solution 2]
Store standard config.username, config.password somewhere else and after the sentinel phase is done, overwrite creds back to the standard creds.

IMHO the cleaner option is solution 1 as that's a common practice to differentiate these options. E.g see this: https://github.com/redis/rueidis/blob/main/sentinel.go#L24 where they differentiate between mOpts (master opts) and sOpts (sentinel opts) I believe.

Please, refer to this urgently.

**Comment by mcatanzariti** [comment]
Hi @wojciechbator,

Thank you for this report. I agree with you that the best solution 1 is the first one.

If it's an urgent matter for you, would you be able to provide a pull request?

Thank you,

Michaël

**Comment by wojciechbator** [comment]
Hi @mcatanzariti,

Sure, I'm happy to help and create a PR when I have a bit time to spare.

Thanks

**Comment by mcatanzariti** [comment]
Hi @wojciechbator,

Would it be ok, when connecting to the master node, to use username/password from the root config:
https://github.com/dahomey-technologies/rustis/blob/29b2b5f66f058bec3b8374fec6eb548b1f2ce472/src/client/config.rs#L28-L45

It would prevent to add new parameters to the rustis config.

Thank you,

Michaël

**Comment by mcatanzariti** [comment]
@wojciechbator,

Please could you check the PR corresponding to my last message: https://github.com/dahomey-technologies/rustis/pull/63

Thank you!

Michaël

**Comment by wojciechbator** [comment]
Hey, yes it looks ok. Thanks for the fix.
