### ISSUE TITLE
PubSubStream subscribe/unsubscribe while iterating

### ISSUE THREAD

**Issue by richardhenry** [dahomey-technologies/rustis#57]
Thanks for open sourcing this library!

My application has these requirements for Pub/Sub (which I don't think are particularly unusual):
- I don't know which pub/sub channels I'm going to subscribe to ahead of time
- I need to subscribe/unsubscribe to channels over time, while continuing to listen to messages on a connection

I have a hacky solution built on top of Rustis right now that looks kind of like this:

``` rust
enum PubSubCmd {
    Subscribe(String),
    Unsubscribe(String),
}

async fn listen() -> Result<(), Error> {
    // We don't yet have any channels to subscribe to, so subscribe to a "void" channel just so that we can get a PubSubStream.
    let mut stream = redis_con().await?.subscribe("void").await?;

    // Retain cmd_tx somewhere and use it to send subscribe/unsubscribe commands.
    let (cmd_tx, mut cmd_rx) = mpsc::channel::<PubSubCmd>(32);

    loop {
        let cmd: Option<PubSubCmd>;

        loop {
            select! {
                value = stream.next() => {
                    if let Some(msg) = value {
                        // I'm handling a message here...
                    } else {
                        // The Redis pub/sub connection was dropped and we can exit.
                        cmd = None;
                        break;
                    }
                }
                value = cmd_rx.recv() => {
                    // If value is Some: Break out of the inner loop, update the connection, then listen again.
                    // If value is None: The cmd_tx was dropped and we can exit.
                    cmd = value;
                    break;
                }
            }
        }

        match cmd {
            Some(PubSubCmd::Subscribe(channel)) => stream.subscribe(channel).await?,
            Some(PubSubCmd::Unsubscribe(channel)) => stream.unsubscribe(channel).await?,
            None => return Ok(()), // Exit
        };
    }
}
```

This seems a lot more complicated than necessary. Looking through the library code, it seems like ideally I could do something like this instead:

1. Connection could have a `pub_sub()` method that returns a `PubSubStream` without subscribing to anything immediately.
2. `PubSubStream` already uses an mpsc channel internally, and seems like it could fairly easily support a `split()` method to allow listening in one async task while sending subscribe/unsubscribe commands from another.

Does something like this make sense? Let me know what you think. Thanks!

**Comment by mcatanzariti** [comment]
Hi @richardhenry,

The design behind `PubSubStream` is that it is created on a first subscription because under the hood, Redis switches an existing connection to pub sub mode only when a first subscription is received by the server.
On the opposite, the connection is switched back to the regular mode when the last unsubscription is received by the server, which is represented by the closing or dropping of the `PubSubStream` instance.
One of the pillars of Rustis is to stick to Redis' design in an as thin as possible layer.

I don't sync your design is bad. If what you need is a background task to subscribe, unsubscribe and listen to events, it is totally ok to keep a stream inside the task and send commands to the task via a mpsc. I think you don't need to create a fake channel subscription. You could hold the stream as on option and actually create it whenever the first subscription command is received.

I'm not sure the design you are requesting would be that much simpler. Would you mind rewriting your example with the design you propose ?

Cheers,

Michaël

**Comment by richardhenry** [comment]
Thanks, this is good feedback around not needing the "void" channel, you're right. My implementation now looks like below. 

``` rust
let mut stream: PubSubStream;
let mut channels: HashSet<String> = HashSet::new();

loop {
    match self.cmd_rx.recv().await {
        Some(FetchCmd::Subscribe(channel)) => {
            channels.insert(channel.clone());
            stream = redis_con().await?.subscribe(channel).await?;
            break;
        }
        Some(_) => (),
        None => return Ok(()),
    }
}

loop {
    let cmd: Option<PubSubCmd>;

    loop {
        select! {
            value = stream.next() => {
                if let Some(msg) = value {
                    // Handle msg...
                } else {
                    // The Redis pub/sub connection was dropped. Exit.
                    cmd = None;
                    break;
                }
            }
            value = self.cmd_rx.recv() => {
                // If value is Some: Break out of the inner loop, update the connection, then listen again.
                // If value is None: The cmd_tx owned by FetchPub was dropped. Exit.
                cmd = value;
                break;
            }
        }
    }

    match cmd {
        Some(FetchCmd::Subscribe(channel)) => {
            if channels.insert(channel.to_owned()) {
                stream.subscribe(channel).await?;
            }
        }
        Some(FetchCmd::Unsubscribe(channel)) => {
            if channels.remove(&channel) {
                stream.unsubscribe(channel).await?;
            }
        }
        None => return Ok(()),
    };
}
```

I guess I agree that this isn't bad, but it does feel like this interface could be quite a bit nicer if the library allowed you to "split" the PubSubStream. I was imagining something like:

```
let mut stream = redis_con().await?.subscribe("channel").await?;
let (listener, manager) = stream.split();

// Retain the listener somewhere else and allow calling subscribe() or unsubscribe() directly on it from another async task.

// We can then block this task to listen for messages, and not worry about subscribing/unsubscribing.
while let Some(Ok(msg)) = stream.next().await { {
    // Handle message.
}
```

The `split()` method is part of the StreamExt trait. Here's an example of a split stream in tokio-tungstenite, where you have one half for sending websocket messages and another half for receiving them: https://github.com/snapview/tokio-tungstenite/blob/master/examples/client.rs#L32

**Comment by mcatanzariti** [comment]
@richardhenry You're right, it is worth thinking about splitting the pub sub stream.

**Comment by mcatanzariti** [comment]
Hi @richardhenry,

Could you please check https://github.com/dahomey-technologies/rustis/commit/395014c1ce42df6d053c774c56d06b1b70532903 and let me know if all is ok for you ?

I finally added a `Client::create_pub_sub()` method.

**Comment by richardhenry** [comment]
Cool, thanks! I'll try migrating my code over to this and let you know how it goes.

**Comment by mcatanzariti** [comment]
ok I will wait for your feedback before publishing a new release

**Comment by richardhenry** [comment]
Just implemented these changes, this is a huge improvement. My code for managing this is about 1/5th the size now. This is the nicest Redis pub/sub API I've used in Rust!

**Comment by mcatanzariti** [comment]
Is it possible that you paste here a sample of your code to see the result, please?
