### ISSUE TITLE
Calling subscribe() multiple times on PubSubStream with the same channel results in an error on close()

### ISSUE THREAD

**Issue by richardhenry** [dahomey-technologies/rustis#59]
If you call subscribe() on PubSubStream multiple times with the same channel the following assertion error will occur when close() is called on the PubSubStream (or when it is dropped):

```
thread 'rocket-worker-thread' panicked at .../src/index.crates.io-6f17d22bba15001f/rustis-0.12.8/src/network/network_handler.rs:545:17:
[localhost:6379] Received unexpected message: Ok(Push([BulkString("unsubscribe"), BulkString("[channel name]"), Integer(0)]))
```

This is fixed by maintaining a hash set of channels in my application code and checking if the channel is already subscribed before calling subscribe, which is a good thing to do anyway — but this would probably be good to fix in Rustis too.

**Comment by mcatanzariti** [comment]
Hi @richardhenry,

I could Indeed create a dedicated error that would be returned by PubSubStream::subscribe if a subscription already exist on the requested channel.

Cheers,

Michaël

**Comment by mcatanzariti** [comment]
fixed in https://github.com/dahomey-technologies/rustis/commit/4109e8a5cfc71a1bbfcbd9b5eee3e54e729705d0
