### ISSUE TITLE
[bug] XREADGROUP command erroneous "mismatched key slots" error with cluster

### ISSUE THREAD

**Issue by richardhenry** [dahomey-technologies/rustis#61]
I'm getting a "Cannot send command XREADGROUP with mismatched key slots" error when using the xreadgroup function with a count provided by XReadGroupOptions against redis cluster. This is odd because I am only using a single key with this command.

My caller looks like this:

```
let read_result: Result<Vec<(String, Vec<StreamEntry<BulkString>>)>, _> = rc
    .xreadgroup(
        &self.group.name,
        &self.name,
        XReadGroupOptions::default().count(1),
        [&stream],
        [&cursor],
    )
    .await;
```

When I turn on debug logging for rustis, I see the following in my logs:

```
[...] Analyzing command Command { name: "XREADGROUP", args: CommandArgs { args: ["GROUP", "[group name]", "[consumer name]", "COUNT", "1", "STREAMS", "[stream name]", "0"] } }
[...] keys: ["COUNT", "1"], slots: [1092, 9842]
[...] Error while writing batch: Client error: [...] Cannot send command XREADGROUP with mismatched key slots
```

It looks like the keys are erroneously being extracted as ["COUNT", "1"] instead of the stream name.

**Comment by richardhenry** [comment]
I've added a failing test case here, I'm trying to figure out what's going on: https://github.com/richardhenry/rustis/commit/1f3cd5b5968974e497996c5f564b44fb7ae5d21b

**Comment by richardhenry** [comment]
I'm pretty sure I've fixed this bug here, and the failing test is passing now: https://github.com/richardhenry/rustis/commit/2522e5009a29770cf7a01acd11bdfc25667f3611

I'll open a PR

**Comment by mcatanzariti** [comment]
Hi @richardhenry,

Good catch!
Thank you for the PR

**Comment by richardhenry** [comment]
Thanks for releasing this so quickly @mcatanzariti. Fyi looks like the 0.12.8 release is still tagged as the latest, rather than 0.12.9, not sure if that's intentional.

**Comment by mcatanzariti** [comment]
The tag on github will be updated at a point. If you go to   https://crates.io/crates/rustis, it's all good!

**Comment by richardhenry** [comment]
Ok thanks!
