### ISSUE TITLE
Busy loop at disconnect

### ISSUE THREAD

**Issue by immerhart** [dahomey-technologies/rustis#66]
Hey, first, thanks for the lib, much appreciated! 

I did a connect to redis like this:

```let redis_cli = Client::connect("127.0.0.1:6379").await;```

which works just fine, if the redis server is running.
But if I kill redis (while still connected), I get error spamming in the console

```
2024-04-02T00:05:33.200878Z ERROR rustis::network::network_handler: [127.0.0.1:6379] Failed to reconnect: IO("[connection refused] Connection refused (os error 111)")    
2024-04-02T00:05:33.200896Z ERROR rustis::network::network_handler: [127.0.0.1:6379] Failed to reconnect: IO("[connection refused] Connection refused (os error 111)")    
2024-04-02T00:05:33.200914Z ERROR rustis::network::network_handler: [127.0.0.1:6379] Failed to reconnect: IO("[connection refused] Connection refused (os error 111)") 
```

Is there some way around this?
Not sure how the reconnect logic is for that case, but it seems like a busy loop?

**Comment by mcatanzariti** [comment]
Thank for the report.
I will take a look at it.
I think the best thing is to add a reconnection timeout with a decent default value in the rustis config

**Comment by immerhart** [comment]
Thanks for the quick response. I would suggest smth. like:
https://en.wikipedia.org/wiki/Exponential_backoff
Or do you mean there is some config I forgot to set?

**Comment by mcatanzariti** [comment]
I mean it has to be implemented!
And exponential back off is definitely something to consider

**Comment by immerhart** [comment]
> I mean it has to be implemented! And exponential back off is definitely something to consider

Hey, do you have any plans to add this soon?

**Comment by mcatanzariti** [comment]
Hello, I'm working on it!

**Comment by immerhart** [comment]
> Hello, I'm working on it!

Cool, not yet so firm in rust, but I can at least do some manual testing... :)

**Comment by immerhart** [comment]
Thanks, works like a charm!
But the "send while disconnected" (like calling e.g. `get`, if redis shutdown) behavior has changed, right? In the previous implementation it was returning an error, now it seems to block.
But that is controllable over the `command_timeout`...

**Comment by mcatanzariti** [comment]
If you don't set the `retry_on_error` flag in the config or in the command, it should not block. Does it?

**Comment by immerhart** [comment]
> If you don't set the `retry_on_error` flag in the config or in the command, it should not block. Does it?

I didn't set that...
With this, it blocks for one second and after that returns the error:
 ```
    let mut c : rustis::client::Config = config.into_config().unwrap();
    c.reconnection = rustis::client::ReconnectionConfig::Exponential { 
        max_attempts: 0,
        min_delay: 100, 
        max_delay: 8000, 
        multiplicative_factor: 2, 
        jitter: 50
    };
    c.command_timeout = Duration::from_secs(1);
```

**Comment by mcatanzariti** [comment]
Ok, I'm going to take a look at it

**Comment by mcatanzariti** [comment]
Should be fixed in https://github.com/dahomey-technologies/rustis/commit/012a1233fadcb1b31df49a7aa99dcc4e358e0a9d
