### ISSUE TITLE
[bug] use "json_arrlen" called `Result::unwrap()` on an `Err` value: Client("Cannot parse to sequence a RESP value starting with :")

### ISSUE THREAD

**Issue by heiky** [dahomey-technologies/rustis#71]
code: 
```
match REDIS_CONNECT.get().await {
        Some(client) => {
            let len = client.json_arrlen::<String,String, Vec<Option<usize>>>(STRATEGY_KEY.to_string(), ".".to_string()).await.unwrap();
            println!("===handler_add_strategy==len={:?}",len);
        },
        _ => {}
    }
````
error:  called `Result::unwrap()` on an `Err` value: Client("Cannot parse to sequence a RESP value starting with :")

**Comment by mcatanzariti** [comment]
Hi,

Please could you provide the json document & the json path to help me reproduce the problem?

Thank you

**Comment by mcatanzariti** [comment]
I close this bug as stalled. Please fell free to open it again if you still encounter the issue!

**Comment by mcatanzariti** [comment]
Closed as stale bug. Please feel free to reopen it.
