### ISSUE TITLE
doesn't exists example code for redis methods

### ISSUE THREAD

**Issue by ArtemIsmagilov** [dahomey-technologies/rustis#74]
I'm trying to figure out exactly how to use ACL DRYRUN through additional options. Can we add a small example for each method?

for example get, set, and etc...
```rust
    ```example
    ///     let value: String = client.get("key").await?;
    ///     assert_eq!("value", &value);
    ```
    fn get<K, V>(self, key: K) -> PreparedCommand<'a, Self, V>
    where
        Self: Sized,
        K: SingleArg,
        V: PrimitiveResponse,
        Self: Sized,
    {
        prepare_command(self, cmd("GET").arg(key))
    }
```

https://github.com/dahomey-technologies/rustis/blob/02d5b1a2a5fae05b67d6e76f17c61dc1da3a0dac/src/commands/server_commands.rs#L66

**Comment by ArtemIsmagilov** [comment]
I don't quite understand, do you have the option not to specify arguments that are assumed to be optional by default? It is not obvious whether it is necessary to specify the options or not?

A simple example of `ACL DRY RUN`, we must use username and command, and the rest are not necessarily `arg`. You have a structure with options as this parameter. Can I not pass these parameters as indicated in the documentation.

Unfortunately, other clients decide for the user that yes, you must specify these parameters, we have such a DSL. What do you have in this regard?

- https://github.com/valkey-io/valkey-py/issues/114

**Comment by mcatanzariti** [comment]
Hi @ArtemIsmagilov,

Does this automatic test helps ?
https://github.com/dahomey-technologies/rustis/blob/02d5b1a2a5fae05b67d6e76f17c61dc1da3a0dac/src/tests/server_commands.rs#L55

**Comment by mcatanzariti** [comment]
FYI, it's the transcription of the example given in the official Redis documentation 

https://redis.io/docs/latest/commands/acl-dryrun/

**Comment by ArtemIsmagilov** [comment]
Thank you so much for showing a great example of using `ACL DRYRUN` in the test, this is a great visual example that I need.

I probably expressed the problem incorrectly. I would just like to have a small rust example for each of your commands in the comments. And this comment perfectly refers to the redis commands. There are just not enough examples in the comments above commands.

I am ready to add comments, with your approval of course. And if there is a need for it.

This is not a problem, but a new feature.

**Comment by mcatanzariti** [comment]
@ArtemIsmagilov,

I would be happy if you would like to contribute to the documentation by providing more examples.

You can find examples for each command in the automated test in this folder :

https://github.com/dahomey-technologies/rustis/tree/main/src/tests

Cheers,

Michaël

**Comment by ArtemIsmagilov** [comment]
It is absolutely not difficult and extremely useful.
I would like to have such examples.

![Screenshot from 2024-11-06 11-26-05](https://github.com/user-attachments/assets/ec88824c-6110-4d11-9cc2-7b5181127482)
